### ISSUE TITLE
关于主题的效果

### ISSUE THREAD

**Issue by luosiwei-cmd** [Sanarous/hexo-theme-next5-polished#3]
大佬您好，我的主题的显示效果和您的不一样。

请问一下我的文章页是黄色的，您的则是清爽的白色，我想看看是您后期做了更改吗？

**Comment by Sanarous** [comment]
是的，主题是去年上传的，后期重新做了修改后没有上传到github发自我的华为手机-------- 原始邮件 --------发件人： luosiwei-cmd <notifications@github.com>日期： 2020年4月26日周日 09:56收件人： Sanarous/hexo-theme-next5-polished <hexo-theme-next5-polished@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [Sanarous/hexo-theme-next5-polished] 关于主题的效果 (#3)

大佬您好，我的主题的显示效果和您的不一样。

请问一下我的文章页是黄色的，您的则是清爽的白色，我想看看是您后期做了更改吗？

**Comment by luosiwei-cmd** [comment]
@Sanarous 那您……能安排上传吗/kk

**Comment by Sanarous** [comment]
> @Sanarous 那您……能安排上传吗/kk

这个现在不行哦，因为疫情问题一直在家，但是博客源码在学校的电脑上，现在无法上传
